//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblTropicalUser
    {
        public int UserID { get; set; }

        [DisplayName("Login ID:")]
        [Required(ErrorMessage="This field is required.")]
        public string LoginID { get; set; }

        [DisplayName("Password:")]
        //let the password be covered
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required.")]
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> UserRouteNumber { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Email { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
